In [2]:

import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("HousingData.csv")
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
data.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,NaN,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,NaN,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [5]:
data.tail(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6,391,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
data.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [7]:
avg_crim=data['CRIM'].astype('float').mean(axis=0)
data['CRIM'].replace(np.nan,avg_crim,inplace=True)

In [8]:
data.isnull().sum()

CRIM        0
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [9]:
avg_zn=data['ZN'].astype('float').mean(axis=0)
data['ZN'].replace(np.nan,avg_zn,inplace=True)

In [10]:
avg_indus=data['INDUS'].astype('float').mean(axis=0)
data['INDUS'].replace(np.nan,avg_indus,inplace=True)

In [11]:
avg_chas=data['CHAS'].astype('float').mean(axis=0)
data['CHAS'].replace(np.nan,avg_chas,inplace=True)

In [12]:
avg_age=data['AGE'].astype('float').mean(axis=0)
data['AGE'].replace(np.nan,avg_age,inplace=True)

In [13]:
avg_lstat=data['LSTAT'].astype('float').mean(axis=0)
data['LSTAT'].replace(np.nan,avg_lstat,inplace=True)

In [14]:
data.notnull().sum()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
MEDV       506
dtype: int64

In [15]:
x = data.iloc[:,0:13]
y = data.iloc[:,-1]

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 13)
(102, 13)
(404,)
(102,)

In [18]:
from sklearn.linear_model import LinearRegression

In [20]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())
model.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [21]:
acc=model.score(x_test,y_test)
print("Accuracy",acc*100)

0.6588520195508119

In [22]:
pred_values=model.predict(x_test)
pred_values

array([ 2.91432496e+01,  3.65356675e+01,  1.44925129e+01,  2.50811104e+01,
        1.84560923e+01,  2.30104937e+01,  1.81386861e+01,  1.46265167e+01,
        2.21158938e+01,  2.08706364e+01,  2.50758640e+01,  1.87470982e+01,
       -5.67498472e+00,  2.17286655e+01,  1.90464014e+01,  2.54293420e+01,
        1.96620047e+01,  6.12420178e+00,  4.09972355e+01,  1.72352716e+01,
        2.48905259e+01,  3.02961849e+01,  1.18008779e+01,  2.29655895e+01,
        1.73451595e+01,  1.51051621e+01,  2.10901065e+01,  1.44883316e+01,
        2.30923960e+01,  1.94365043e+01,  2.25439953e+01,  2.52375663e+01,
        2.59309510e+01,  1.66289054e+01,  1.64513986e+01,  1.66143478e+01,
        3.11105960e+01,  2.02837991e+01,  2.43569451e+01,  2.26326769e+01,
        1.45257750e+01,  3.23698301e+01,  4.30428488e+01,  1.76390763e+01,
        2.76326197e+01,  1.64305143e+01,  1.42484248e+01,  2.61635938e+01,
        1.97678160e+01,  3.01463483e+01,  2.09688785e+01,  3.38338873e+01,
        1.64161397e+01,  2.63964842e+01,  3.97974153e+01,  2.20563187e+01,
        1.86348862e+01,  3.28326904e+01,  2.54125467e+01,  1.30089663e+01,
        2.27876091e+01,  3.07563535e+01,  3.14152535e+01,  1.63140433e+01,
        2.03393413e+01,  1.71517970e+01,  2.01806664e+01,  2.61876399e+01,
        3.09535452e+01,  1.13750175e+01,  2.09535826e+01,  2.65775894e+01,
        1.10320126e+01,  1.28353764e+01,  2.37619366e+01,  6.45053524e+00,
        2.16940761e+01,  4.17751699e+01,  1.87002180e+01,  8.80916013e+00,
        2.09823382e+01,  1.32224442e+01,  2.09744123e+01,  9.19727517e+00,
        2.29748473e+01,  3.23665383e+01,  1.90112841e+01,  2.56021909e+01,
        2.86884146e+01,  1.97639493e+01,  2.59912517e+01,  5.78236486e+00,
        1.94886094e+01,  1.52277879e+01,  1.07368355e+01,  2.00495289e+01,
        2.37375593e+01,  2.87336882e-02,  1.35379379e+01,  1.60971385e+01,
        2.27958041e+01,  2.43808232e+01])

In [23]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,pred_values)
print('Accuracy',accuracy*100)

Accuracy 65.88520195508119

In [24]:
user_input = {}
for column in x.columns:
    user_input[column] = float(input(f"Enter the value for {column}: "))
user_df = pd.DataFrame([user_input])

user_pred = model.predict(user_df)
print("Predicted price:", user_pred[0])

Enter the value for CRIM: 0.00632
Enter the value for ZN: 18.0
Enter the value for INDUS: 2.31
Enter the value for CHAS: 0
Enter the value for NOX: 0.538
Enter the value for RM: 6.575
Enter the value for AGE: 65.2
Enter the value for DIS: 4.09
Enter the value for RAD: 1
Enter the value for TAX: 296
Enter the value for PTRATIO: 15.3
Enter the value for B: 396.9
Enter the value for LSTAT: 4.98
Predicted price: 30.146348293075807

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv("HousingData.csv")
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [42]:
data.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [34]:
avg_crim=data['CRIM'].astype(float).mean(axis=0)
avg_crim
data['CRIM'].replace(np.nan,avg_crim,inplace=True)

In [35]:
avg_zn=data['ZN'].astype(float).mean(axis=0)
avg_zn
data['ZN'].replace(np.nan,avg_zn,inplace=True)

In [37]:
avg_indus=data['INDUS'].astype(float).mean(axis=0)
avg_indus
data['INDUS'].replace(np.nan,avg_indus,inplace=True)

In [38]:
avg_chas=data['CHAS'].astype(float).mean(axis=0)
avg_chas
data['CHAS'].replace(np.nan,avg_chas,inplace=True)

In [39]:
avg_age=data['AGE'].astype(float).mean(axis=0)
avg_age
data['AGE'].replace(np.nan,avg_age,inplace=True)

In [41]:
avg_lstat=data['LSTAT'].astype(float).mean(axis=0)
avg_lstat
data['LSTAT'].replace(np.nan,avg_lstat,inplace=True)

In [44]:
data.shape

(506, 14)

In [46]:
x=data.iloc[:,0:13]
y=data.iloc[:,-1]

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print('X_Test shape',x_test.shape)

X_Test shape (102, 13)

In [60]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
model=make_pipeline(StandardScaler(with_mean=False),LinearRegression())
model.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [61]:
model.score(x_test,y_test)

0.6588520195508119

In [62]:
import pandas as pd
import numpy as np

In [63]:
data=pd.read_csv("HousingData.csv")
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [64]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [74]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [73]:
avg_crim=data['CRIM'].astype(float).mean(axis=0)
print(avg_crim)
data['CRIM'].replace(np.nan,avg_crim,inplace=True)
avg_zn=data['ZN'].astype(float).mean(axis=0)
print(avg_zn)
data['ZN'].replace(np.nan,avg_zn,inplace=True)
avg_indus=data['INDUS'].astype(float).mean(axis=0)
print(avg_indus)
data['INDUS'].replace(np.nan,avg_indus,inplace=True)
avg_chas=data['CHAS'].astype(float).mean(axis=0)
print(avg_chas)
data['CHAS'].replace(np.nan,avg_chas,inplace=True)
avg_lstat=data['LSTAT'].astype(float).mean(axis=0)
print(avg_lstat)
data['LSTAT'].replace(np.nan,avg_lstat,inplace=True)
avg_age=data['AGE'].astype(float).mean(axis=0)
print(avg_age)
data['AGE'].replace(np.nan,avg_age,inplace=True)

3.611873971193416
11.211934156378602
11.083991769547326
0.06995884773662552
12.715432098765433
68.51851851851852

In [76]:
x=data.iloc[:,0:13]
y=data.iloc[:,-1]
print('x',x.shape)
print('y',y.shape)

x (506, 13)
y (506,)

In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print('X_train shape ',x_train.shape)

X_train shape  (404, 13)

In [84]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
model = make_pipeline(StandardScaler(with_mean=False),LinearRegression())
model.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [85]:
acc=model.score(x_test,y_test)
print('accuracy 'acc)

0.6588520195508119

In [92]:
import pandas as pd
import numpy as np

In [93]:
data=pd.read_csv("HousingData.csv")
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [94]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [98]:
data.isna().sum()

CRIM        0
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [99]:
avg_crim=data['CRIM'].astype(float).mean(axis=0)
print(avg_crim)
data['CRIM'].replace(np.nan,avg_crim,inplace=True)
avg_zn=data['ZN'].astype(float).mean(axis=0)
print(avg_zn)
data['ZN'].replace(np.nan,avg_zn,inplace=True)
avg_indus=data['INDUS'].astype(float).mean(axis=0)
print(avg_indus)
data['INDUS'].replace(np.nan,avg_indus,inplace=True)
avg_chas=data['CHAS'].astype(float).mean(axis=0)
print(avg_chas)
data['CHAS'].replace(np.nan,avg_chas,inplace=True)
avg_age=data['AGE'].astype(float).mean(axis=0)
print(avg_age)
data['AGE'].replace(np.nan,avg_age,inplace=True)
avg_lstat=data['LSTAT'].astype(float).mean(axis=0)
print(avg_lstat)
data['LSTAT'].replace(np.nan,avg_lstat,inplace=True)

3.611873971193416
11.2119341563786
11.083991769547325
0.06995884773662552
68.51851851851852
12.715432098765433

In [100]:
x=data.iloc[:,0:13]
y=data.iloc[:,-1]
print(x.shape)
print(y.shape)

(506, 13)
(506,)

In [101]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
print(x_train.shape)

(404, 13)

In [102]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [110]:
acc=model.score(x_test,y_test)
print(acc*100)

71.18534507409738

In [105]:
predict=model.predict(x_test)
print(predict)

[12.65954326 27.04858715 18.00920889 18.88573278 32.79163467 25.44019386
 31.12462746 19.29421327 20.64330593 23.21298335 28.22843041 28.41366623
 19.00444532 32.21066234 21.65303358 15.17155501 21.37089631 11.65333773
 11.10935271 14.01116614  5.915496   17.07783166 19.8187971  22.76750968
 17.07947186 20.84842203 18.5759997  13.96437683 20.67820436 17.89379068
 14.42141713 24.09121881 34.46251071 21.19178376 16.39130145 19.94265066
 31.03012602 31.9442619  23.53169736 24.59389672 37.12956577 32.11188867
 18.75080735 31.61395898 33.97821179 25.60676217 40.65176291 18.35100131
 18.94506764 24.0600269  33.12831029 25.65262115 17.84437106 27.91814116
 13.14223269 23.43237876 24.68729803 33.31099703 16.98236263 36.85801318
 16.4194925  18.14911437 32.30961504 15.27385266 38.98858888 27.51612187
 31.88425141 10.29128008 18.69877088 21.23596004 23.59323229 23.19729601
 22.73584039 28.29791954 17.17583424 23.63900839 16.42404163 25.17979962
 14.0593415  20.16034441 22.42982446 19.89675128 28.50115122 19.59649572
 30.35827384 22.29270548 30.45635187 19.48541244 24.3226119  38.30986308
 30.8514964  41.65575901 18.78721146 37.5008154  19.95537799 23.40062387
 27.11226027 21.75765203  9.60222979 20.59762104  9.34112761 27.57809835]

D:\Jupiter\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.